#!/bin/sh

exec < /dev/tty 2&1 || echo "Commit message invalid!"
MESSAGE=`cat .git/COMMIT_EDITMSG`

function patternCheck(){
	COMMIT_MESSAGE=$1
	if [[ ! "$COMMIT_MESSAGE" =~ ([a-zA-Z]{2})(-[0-9]{4}) ]];then
		echo "Commit message invalid!\nShould match [A-Z]{2}-[0-9]{4}*"
		echo "Please enter a new MESSAGE"
		read NEW_MESSAGE || exit 2
		patternCheck "$NEW_MESSAGE"
	else
		COMMIT_MESSAGE=$COMMIT_MESSAGE
	fi
	echo  "$COMMIT_MESSAGE" > ".git/COMMIT_EDITMSG"
  	exit 0
}

patternCheck $MESSAGE